console.log("Andrade obteve as seguintes notas durante os 4 bimestres: ");
var bi1 = 7;
var bi2 = 6;
var bi3 = 5.5;
var bi4 = 9;
console.log("1º bimestre: " + bi1);
console.log("2º bimestre: " + bi2);
console.log("3º bimestre: " + bi3);
console.log("4º bimestre: " + bi4);
var media = (bi1 * 1 + bi2 * 2 + bi3 * 3 + bi4 * 4) / (1 + 2 + 3 + 4);
console.log("Sabendo que o peso de cada nota é de acordo com o bimestre, sua media final foi: " + media);